FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Install Prisma CLI
RUN npm install prisma --save-dev

# Bundle app source
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Run migrations
CMD ["npx", "prisma", "migrate", "deploy"]
